### ISSUE TITLE
[BUG] Potential bug in Basket component

### ISSUE THREAD

**Issue by ov-i** [Jakub-Klejczyk/LoginToShopProject#2]
# About issue
This issue is connected with Basek component, located in **src/components/Basket.vue**.
In default export definition, the "data()" function, has been declared with empty. body, but it should return at least an empty object
like so

```js
data: () => ({})
```
or

```js
data() {
  return {}
}
```

# How to reproduce this bug?
Go to built in console in your web browser, when you are located in store tab

**Comment by Jakub-Klejczyk** [comment]
Done
